### PR TITLE
feat: Implement Aggregate functions

### PR DESCRIPTION
**Pull request by donkizzy**
## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by codekeyz** [comment]
@donkizzy I think you're touching alot of files here. Fix the dart formatting length and undo the changes in un-related files.

**Comment by donkizzy** [comment]
@codekeyz i have reverted it to 80 and restored the old formatting on un related files

**Comment by donkizzy** [comment]
@codekeyz there is an error with the ORM CLI so the integration tests can't run, check discord, I shared a snippet with you

**Review by codekeyz — APPROVED** [review]
Awesome work 🚀. Really love how the implementation turned out @donkizzy

**Pull request merged**
